# Generated by Django 4.2.6 on 2023-11-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('care', models.TextField(blank=True)),
                ('plantDate', models.DateField()),
                ('box', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garden_app.planter')),
            ],
        ),
    ]
