# Generated by Django 4.2.6 on 2023-11-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0005_themechanger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeChanger',
        ),
    ]
